### ISSUE TITLE
CachingService should not share CachingProvider

### ISSUE THREAD

**Issue by GeeWee** [alastairtree/LazyCache#102]
I'd like to use the real CachingService in unit tests, because I want to test cache interactions. I write my test like this

```csharp
var cachingService = new CachingService();
// do something with it
```
And I do that in multiple tests. However due to the fact that CachingService instantiates a static lazy CachingProvider in `DefaultCacheProvider` - the tests end up sharing the same CachingProvider.

I think optimally we'd create a new CachingProvider per CachingService

**Comment by alastairtree** [comment]
Your use case makes sense for tests, but not really in an app where you would probably use dependency injection with a shared provider or configure the DI container to achieve this sort of unusal behaviour. 
If you want to build a totally new cache in your tests, you should build it manually like this, probably in a method so you dont repeat the code in every test.

```csharp
var cachingService = new CachingService(
               new MemoryCacheProvider(
                    new MemoryCache(
                        new MemoryCacheOptions()
                    )
              )
       );
```

**Comment by GeeWee** [comment]
I agree - but in the app, isn't the actual IAppCache instantiated as a singleton - or is that too app-specific to tell?

I'm fine with not accepting this change, but I think we should consider changing the unit test documentation to mention this. Thoughts?
