### ISSUE TITLE
Factory method is being called more than once in a parallel context

### ISSUE THREAD

**Issue by leandromoh** [alastairtree/LazyCache#109]
I am having trouble with race codition with `LazyCache` because factory method is being called more than once in a parallel context. So I found this [article](https://blog.novanet.no/asp-net-core-memory-cache-is-get-or-create-thread-safe/) about the behavior of the `GetOrAdd` method of this lib, and note that the output showed in the article was `3 3 3 3 3 3 3 3 3 3`! But should not lazy cache call factory method once? Thus outputting  `1 1 1 1 1 1 1 1 1 1` ?  

that is, should not lazy cache use `lock` to invoke call back only once? As mentioned in the article 

> To fix this LazyCache uses more aggressive locking to ensure the delegate only fires once.

and in this [stackoverflow answer](https://stackoverflow.com/a/40089949)

> The second thread should wait for the first to complete and use its result rather than generating results twice. This was one of the reasons I wrote LazyCache

If this lib does not guarantees execute the delegate to prime the cache only once in a multi-thread enviroment, how can I get this behavior on my local application?

**Comment by alastairtree** [comment]
I assume that must be a typo becasue yes I would expect only 1 to be returned. We have a unit tests that validates this exact behaviour at https://github.com/alastairtree/LazyCache/blob/master/LazyCache.UnitTests/CachingServiceMemoryCacheProviderTests.cs#L213 and it passes on every build.

So I dont think this is a bug unless you have a reproducible example of that behaviour?

**Comment by migr1** [comment]
> But should not lazy cache call factory method once? Thus outputting 1 1 1 1 1 1 1 1 1 1 ?

Not really, since Parallel.ForEach(Enumerable.Range(1, 10), ...) creates 10 tasks that will run in parallell, but which one of the tasks that is executed first is not deterministic. 
As long as the output consists of only one and the same number, LazyCache works correctly.

**Comment by alastairtree** [comment]
Ok, so yes it might be the case that the third task of ten happens to be the first thread that executes the cache delegate - and so that's why the linked article is outputting 3s - it is the task number and not the number of times it has been executed. but certainly only one of those 10 tasks will actually execute the cached delegate Func a single time, and after that the cached result is reused.

Please file a bug, ideally with a failing unit test example, if you think this is not the case.

Thanks for the discussion.

**Comment by leandromoh** [comment]
in the code bellow (from the article I posted), to `counter` values `3`, was not the factory method invoked 3 times?

```c#
int counter = 0;

            Parallel.ForEach(Enumerable.Range(1, 10), i =>
            {
                var item = cache.GetOrCreate("test-key", cacheEntry =>
                {
                    cacheEntry.SlidingExpiration = TimeSpan.FromSeconds(10);
                    return Interlocked.Increment(ref counter);
                });

                Console.Write($"{item} ");
            });
```

**Comment by alastairtree** [comment]
Anything other than one would be a bug I think. Are you able to submit a reliable failing unit test?

**Comment by jackfox10** [comment]
Hi all,

I recreated the same bug when calling getOrAdd and getOrAddAsync in parallel using version 2.1.2. When calling GetOrAdd or GetOrAddAsync in parallel, the factory should only be called once however the below test shows that the factory is called every single time.

@alastairtree in the unit test you linked, you are kicking off the tasks in order and then waiting for them both to complete. This guarantees the factory is called once  but it does not guarantee thread safety in a parallel environment. 

The following unit test will fail (should pass):

```
[Test]
        public void ParallelCallsShouldNotCauseMultipleMisses()
        {
            var testResultArray = new int[10];
            int counter = 0;

            Parallel.ForEach(Enumerable.Range(1,10), i =>
            {
              var item = sut.GetOrAdd("test-key", entry => Interlocked.Increment(ref counter));
              testResultArray[i-1] = item;
            }

          Assert.AreEqual(1, testResultArray.Distinct().Count())
        }
```

**Comment by alastairtree** [comment]
Yes that makes sense - the mock instance is just that, a mock, with no locking or smarts whatsoever! Will close as i think this is resolved. Thanks for commenting.
