### ISSUE TITLE
A single cache for multiple datasets

### ISSUE THREAD

**Issue by danleydmello** [alastairtree/LazyCache#114]
This not an issue but a question for my use case.
I working on an application that gets data from multiple sources (rest APIs) . Each dataset is different and should be cached. Ideally, I would like to cache each dataset in its own memory cache so that I don't have to worry about key collision, each key is guid, but Microsoft does not recommend creating multiple instance of memory cache. While exploring a solution for cache, I came across LazyCache. I am quite interested in using Lazycache as its very simple API and takes care of synchronization. If my application injects LazyCache (I assume its singleton), what's the best practice I can use to generate the keys because now different datasets will be stored in the same Cache and I want to make sure the keys are unique.

For example: Let say I am storing users and orders in the same cache. Key for the user will be userId (guid) and Orders will be OrderId (guid). Can I do something like this : User Key = "User_xxxx_Xxxx_Xxx_Xxx" OrderKey = "Order_xxx_xxx_Xx_xxxx" Or there is better way to do it?

**Comment by njy** [comment]
Well, I mean, adding a prefix is surely ok but if you are convinced you can have guids collisions I think you have other problems to solve 😅 (see https://stackoverflow.com/questions/184869/are-guid-collisions-possible/185001 )

![image](https://user-images.githubusercontent.com/1010086/79669022-10434b80-81b9-11ea-8f4c-7c1b99280b34.png)

**Comment by alastairtree** [comment]
If you are on the older .NET framework and LazyCache < 1.0 then yes the advice is that a single instance of MemoryCache is prefered. 
If you are on .net core and newer version of LazyCache then having muttiple instance of the underlying MemoryCache are fine, and recommended if you need to be able to dispose of one set of items seperately from the others.
However I agree with @njy - cache keys using guids are fine and not going to colide, but sometimes a cache key prefix is useful anyway so you could iterate through the keys and know which items belong to which area of the application.
Does that solve your question?

**Comment by danleydmello** [comment]
Thanks @njy and @alastairtree , I am using .netstandard 2.0 and surely I can use latest version of LazyCache. If it is fine to use multiple instances of MemoryCache in .netstandard then I will be happy to go with this approach. 

Regards
Danley
