### ISSUE TITLE
Infinite Cache Duration

### ISSUE THREAD

**Issue by Brondahl** [alastairtree/LazyCache#115]
[Use the Thumbs Up reaction to vote for this feature, and please avoid adding comments like "+1" as they create noise for others watching the issue.]

I want to setup a cache with no expiration in its DefaultCachePolicy

I'm currently using:
```
                myCachingService.DefaultCachePolicy = new CacheDefaults
                {
                    DefaultCacheDurationSeconds = xxxx
                }
```
I don't know whether I should be setting that `xxxx` to ... `0`?, `-1`? `int.MaxValue`? `TenYearsInSeconds` etc.

`int.MaxValue` is my instinct, but in the absence of docs, I don't know whether that is at risk of triggering any overflow issues in some situations.

Please can we have some docs about what to do in this situation.
Or even better, can we have `TimeSpan` support on that property. (since that then supports `TimeSpan.Infinite`

**Comment by alastairtree** [comment]
int.MaxValue will be fine and expires in year 2088 which should be fine! Personally though I would pass a static entry options into IAppCache.GetOrAdd which uses [the NeverRemove priority.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheitempriority?view=dotnet-plat-ext-3.1)

```
private static MemoryCacheEntryOptions opts = new MemoryCacheEntryOptions() { Priority = CacheItemPriority.NeverRemove};

....

var things = cache.GetOrAdd("key", () => GetThings(), opts);
``

**Comment by rexcfnghk** [comment]
Was searching for exactly this. Perhaps this should be included in the wiki too?

**Comment by alastairtree** [comment]
Sure thing - https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#caching-items-that-should-not-expire
