### ISSUE TITLE
DefaultCacheDurationSeconds is not being honored

### ISSUE THREAD

**Issue by hermesramos** [alastairtree/LazyCache#121]
**Describe the bug**
DefaultCacheDurationSeconds is not being honored.

**To Reproduce**
`public static readonly IAppCache CachingService = new CachingService { DefaultCachePolicy = new CacheDefaults { DefaultCacheDurationSeconds = 1 } };
`

Even though duration is set to 1 second (this time frame is for testing purpose), no cache entry is being evicted.

**Expected behavior**
Evict all cache entries after 1 second.

** Framework and Platform
 - OS: Windows 10
 - Framework: netcoreapp3.1
 - LazyCache Version: 2.0.4

**Comment by alastairtree** [comment]
By default cache eviction is lazy for performance reasons - eviction is only triggered on the next time the item is accessed. So even though an expired item is still in the cache it will not be used, and eviction will be triggered next time you try and access it, and any post eviction callbacks will fire then. If required you can force immediate expiration using ExpirationMode in LazyCache 2.1, see the [expiration mode section of the docs](https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#expirationmode--immediate-cache-eviction-lazycache-21-upwards) for more info.
