### ISSUE TITLE
Project Health

### ISSUE THREAD

**Issue by svengeance** [alastairtree/LazyCache#123]
Heyo,

I don't mean to insult anyone here because I love everything this project has done and have used it extensively.

@alastairtree Are you still able to commit to maintaining this project? There's a bit of a buildup of issues and pull requests, and I'm wondering what we can do to best help you. If you're in need of anyone to help maintain this project, I would gladly be able to devote some time in its upkeep with issues and PRs, and I'm sure there are others who would likewise do so.

I hope all is well, and thank you again!

**Comment by alastairtree** [comment]
Hello, totally valid question, and thanks for the offer of support. Not had much time to invest over here recently, hence a little stagnation but I do try and keep an eye on it! Will try and clear some of the backlog in the next couple of weeks so feel free to comment/create on issues or submit PRs. If you, or others reading, can demonstrate through PRs, WIKI/Issue contributions that you are willing and compentent then you are right I should add some more contributors.

**Comment by svengeance** [comment]
Awesome, glad to see it! I'll try to become more active 'round here - lord knows I've used this in enough projects I can give back a bit and maybe longer-time as well.

Thank you! I'll close the issue as you've directly answered my questions.
