### ISSUE TITLE
Validate LazyCache works with .NET5 and add new tests for it

### ISSUE THREAD

**Issue by alastairtree** [alastairtree/LazyCache#131]
[Use the Thumbs Up reaction to vote for this feature, and please avoid adding comments like "+1" as they create noise for others watching the issue.]

* .NET 5 is now ready for testing. Is LazyCache still compatible? Any fixes needed? Any value in cross compilation by multi targeting core 5 and netstandard 2? Report back results on here.
* Any breaking changes could/should target a 3.0 release
* Add a new test project to validate compatibility with 5 like the existing core 2/2.1/3/3.1 projects

**Comment by luposky** [comment]
Could I also suggest to validate the Blazor Wasm scenario?
