### ISSUE TITLE
Question: How to prevent GetOrAddItem factory method to NOT store a null Value?

### ISSUE THREAD

**Issue by Pollocks01** [alastairtree/LazyCache#141]
This is a question as opposed to a Bug or feature request and I am a C# noob. What am I missing here?

```
try
{
    Cust = GetOrAddItem(HttpContext, CustomerId, () =>
    {
        Customer customer = Customer.GetCustomer(CustomerId);
        if (customer != null) return customer;
        throw new Exception("CUSTOMER_NOT_FOUND");
    });
}
catch (Exception err)
{
    if (err.Message != "CUSTOMER_NOT_FOUND") throw err;
    return null;
}
```

I found that if instead of throwing that exception, I return null, it caches a null Value to that Key.

I would like to avoid throwing the exception to skip caching of a null object because that seems to take 3 times as long as a successful request to process. I am, however, only running in debug mode at this point.

How to I skip storing a null value?

regards,

Pollocks01

**Comment by alastairtree** [comment]
Your code is missing the GetOrAddItem method contents which must hold the actual call to LazyCache but assuming it is pretty simple and guessing its contents, something like this might do?

```csharp
var key = "customers-" + CustomerId;
Cust = appCache.GetOrAdd(key, () => Customer.GetCustomer(CustomerId));
if(Cust == null) appCache.Remove(key);
```

**Comment by Pollocks01** [comment]
Sorry for the late response. I showed the wrong code (it was a wrapper). My code does look similar to yours above.

The question remains - how to prevent storing the null. Above, you remove the item if it's null but presumably that will occupy an entry in the cache for a a moment and that might cause other items to be purged (if using SizeLimit).

I'd like to skip storing the entry without having to raise an exception to cause that to happen.

Any ideas?

regards,

Pollocks01

**Comment by alastairtree** [comment]
It's not really possible of you want lazy evaluation. In order to stop other threads also getting the customer at the same time you have to put a lazy into the cache so that all threads will wait for one thread to evaluate your delegate and get the customer. If you don't want to cache anything until after you have fetched the customer, do not use GetOrAdd, just use Add once you know the customer is not null.

**Comment by Pollocks01** [comment]
Thanks for the info. I determined (yet to validate) that exception raising performance seems to be related to debug mode and exceptions in production code won't likely take the 400ms + that I see in debug.

Have a great day, and stay safe!
