### ISSUE TITLE
ExpirationMode.ImmediateEviction does not exist in 2.1.2

### ISSUE THREAD

**Issue by joshuadevries** [alastairtree/LazyCache#143]
When I try to use ExpirationMode.ImmediateEviction it does not work. The enum does not contain this option:
![image](https://user-images.githubusercontent.com/63015312/102258118-94320c80-3edb-11eb-8dbc-83a2dc26fd9f.png)

The enum:
![image](https://user-images.githubusercontent.com/63015312/102258181-a3b15580-3edb-11eb-99b3-9a8156772646.png)

I am using version 2.1.2.
![image](https://user-images.githubusercontent.com/63015312/102258095-8bd9d180-3edb-11eb-9666-a8a9948a5853.png)

**Comment by joshuadevries** [comment]
I was able to get this working by using ExpirationMode.ImmediateExpiration. So It looks like its just the documentation that is out of date.

**Comment by alastairtree** [comment]
Thanks for the reminder to update the docs - they were based on the beta version of the api which was `ExpirationMode.ImmediateEviction`, but was changed to `ExpirationMode.ImmediateExpiration` as that is more correct.
