### ISSUE TITLE
Upon expiration, pull data on next Get

### ISSUE THREAD

**Issue by jackjwilliams** [alastairtree/LazyCache#15]
We've started using this in a project, and I am wondering after an item expires, if it's corresponding Func not called again to repopulate? It would be nice if it was kept around to repopulate after expiration.

We are creating a generic cache, where I can key by typeof(T).FullName, with a func to call out to a web api and get the data. It works, until it expires.

Once it expires the web api is never hit again and it's gone forever. I'm guessing I probably just need to keep the func around and use GetOrAddAsync instead of GetAsync.

**Comment by alastairtree** [comment]
Yes you should use GetOrAddAsync in this scenario. The Func<T> factory you pass is only executed on a cache miss, so the first time or the request after expiration. All other times it is not run. See https://github.com/alastairtree/LazyCache/blob/master/Samples/ApiAsyncCachingSample/Controllers/DbTimeController.cs sample for a demonstration of this. Does that answer your question?

**Comment by alastairtree** [comment]
Closing this now, but let me know if you think I should reopen.
