### ISSUE TITLE
Get doesn't call function delegate added with Add

### ISSUE THREAD

**Issue by mtfarkas** [alastairtree/LazyCache#159]
**Describe the bug**
If I add a `Func<T>` factory function to cache via the `Add` method, then later want to retrieve the value it provides via `Get`, the returned value will be a `Func<T>` instead of a value of type `T`.

**To Reproduce**
Add a `Func<T>` to cache via the `Add` method, then retrieve it immediately via the `Get` method.

**Expected behavior**
The factory function is called and the resulting value is returned instead of the function itself.

**Framework and Platform**
 - OS: Windows 10 build 19042.1110
 - Framework: .NET 5.0
 - LazyCache Version: 2.1.3

**Additional context**
N/A

**Comment by jodydonetti** [comment]
That's not a bug, you are using it wrong.

The signature for  the `Add` method is this:

```csharp
void Add<T>(string key, T item, MemoryCacheEntryOptions policy);
```

So by calling `Add` you are _"adding an item to the cache"_ and not _"specifying a factory to be used with a cache key for later retrieval"_.

So basically while you think you are specifying the factory for later use, you are really adding the factory itself (a lambda) to the cache as the item: then when, later on, you ask for the item in the cache it will give you back that item, which is the lambda itself.

Hope this helps.

**Comment by mtfarkas** [comment]
You're entirely right, but for some reason the IntelliSense in Visual Studio shows an overload that does take a Func<T> as a second argument, I can't reproduce this outside of this one project. Thanks for pointing out and sorry for bothering.

**Comment by jodydonetti** [comment]
No worries! Even though this is not my lib now I'm curious about the situation you're talking about, will try to reproduce it out of curiosity.
Best.

**Comment by alastairtree** [comment]
All good then, use the GetOrAdd method for the behaviour you are seeking.
