### ISSUE TITLE
Cache eviction policy when cache is full?

### ISSUE THREAD

**Issue by Masuzu** [alastairtree/LazyCache#169]
What is the cache eviction policy when the LazyCache is full? Is the behaviour configurable?

**Comment by alastairtree** [comment]
As we use dotnet MemoryCache this is controlled by that. You can use sizes and eviction policy to control how the cache  evicts items and when it is "full". MemoryCache does not respond to memory pressure as a trigger to flush the cache so "fullness" is defined by the developer and not the machine. Some more info at https://docs.microsoft.com/en-us/dotnet/core/extensions/caching
