### ISSUE TITLE
GetOrAdd / GetOrAddAsync<T> should return null if the item ADDED.

### ISSUE THREAD

**Issue by PureKrome** [alastairtree/LazyCache#23]
Hi 👋 

(edit: added repo and some more info)

### Summary

Could the `GetOrAddAsync<T> / GetOrAdd<T>` methods return `null` if the item was ADDED. This is what Microsoft does with the `ObjectCache.GetOrAdd(..)` method so this would then follow the same logic.

### Details

Ok, so in this code for GetOrAddAsync<T> (or GetOrAdd...) you internally call the `ObjectCache.AddOrExisting(..)` under the hood to quietly add or get the item from the cache. Great!

[Looking at the MS docs for OC.AOE](https://msdn.microsoft.com/en-us/library/dd988724(v=vs.110).aspx) it says (emphasis mine):

>Return Value
>Type: System.Runtime.Caching.CacheItem
>If a cache entry with the same key exists, the specified cache entry; **otherwise, null**

which also is [confirmed when I step through your code](https://github.com/alastairtree/LazyCache/blob/99f5268a6321ca17a8f49715f84ab76199c894f5/LazyCache/CachingService.cs#L87):

```
// CachingService.cs
var existingCacheItem = ObjectCache.AddOrGetExisting(key, newLazyCacheItem, policy);
```

`existingCacheItem == null` when the item was added.
`existingCacheItem != null` when the item already exists and was retrieved.

It's also a nice _hint_ to the developer to explain if the item was actually ADDED or RETRIEVED (exists). 
i.e.
- If null, then added.
- If not null, then retrieved.

So - what do you think?

Yes, this would be a major semver number increase/change.

--

How to repo:

- Goto the test `GetOrAddAsyncTaskAndThenGetTaskOfAnotherTypeReturnsNull`
- add a breakpoint on line 311.
- add another breakpoint on `CachingService.cs`, line 87.
- Debug...
- After you step over line 87, `existingCacheItem` should equal `null`. This proves the item was added.
- OPTIONAL: Confirm the item is in the cache by looking inside the `ObjectCache` using the visual studio debugger.

**Comment by alastairtree** [comment]
Hi. Thanks for the suggestion. Wondering why you would want that/what problem it solves as i think that change would make the api less productive? The difference between LazyCache and ObjectCache is that in GetOrAddAsync we accept a delegate, not the actual value, so if we are adding to the cache the value has not been constructed yet. That means if we returned null you would not have a reference to it unless you kept hold of one in your delegate which feels messy to me. Or have I miss understood?

**Comment by alastairtree** [comment]
No reply for a while, closing.

**Comment by PureKrome** [comment]
Hi @alastairtree - it's been a while since I used this. So I can't remember the exact use case.

It was along the lines of something like:

- get item from cache.
- if item doesn't exist, then add to cache.
- *now record WHAT happened*

the problem is the last step. I don't know if the item was added or just retrieved. 

I think that's why I created this issue.

**Comment by alastairtree** [comment]
In that case the "record what happened" code can be done inside the callback as that only gets executed when the item is actually generated for the cache?

**Comment by PureKrome** [comment]
I understand what you're suggesting and think that has merit - I just wondered if I had problems with that when I last tried it?

Sample code or some updated docs with an example?
