### ISSUE TITLE
I've forked and retargeted for multiple frameworks, net45, net 46, and netstandard2.0

### ISSUE THREAD

**Issue by GeekActual** [alastairtree/LazyCache#24]
Would you like me to contribute to your library?

I've forked your project and upgraded the solution to support the multiple framework targeting available in Visual Studio 2017, this does make it no longer able to be opened in VS 2015 (that's the downside). On the up side, I've upgraded it to the latest nuget packaging spec, and now have targeted packages for the original net45, but it also now creates and packages up into nuget a native net46 library, and a new native netstandard2.0 library.

The original net45 (and net46) are exactly the same code as the branch I pulled down.

Note the netstandard2.0 no longer supports the `System.Runtime.Caching` library.
For netstandard2.0 the replacement library is the `Microsoft.Extensions.Caching.Memory`

so I had to put in some compiler directives to do some minor spoofing that points to the correct implementation for netstandard2.0. I accomplished this by spoofing the object names so the code looks the same. This approach would allow users of your library to use it in netstandard2.0 (and most importantly Asp.net Core) with no modification in 95% of all cases, but it does sacrifice the clarity that would result if the users were "forced" to use the new specific class names in `Microsoft.Extensions.Caching.Memory`. 

however we are currently using your library and we need to port over to asp.net core asap, so I wanted to make it possible for *our* stuff to be up and running as quick as possible, so I went with the spoofing route, and it just drops in and works in our stuff.

Anyways I wanted to give you the chance to receive these changes and incorporate them if you are interested.

**Comment by alastairtree** [comment]
Hi, thanks. I'm away for a couple of weeks bit I will review this on my return and try and pull it in. Thanks!

**Comment by GeekActual** [comment]
Hello Alastair
Would you still be interested in looking at my netstandard 2.0 implementation fork? I can't submit a pull request, since I'm not a contributor, but I've attached a Zip with my changes.

If you decide to roll this in, please let me know so I can point back to the "Offical" LazyCache nuget package

[LazyCache.zip](https://github.com/alastairtree/LazyCache/files/1467584/LazyCache.zip)

**Comment by johnhamm** [comment]
I put up a MyGet Nuget feed with this alpha version until the official version can be released:
https://www.myget.org/F/lazycache/api/v3/index.json

**Comment by johnhamm** [comment]
@GeekActual:

On line 65 of LazyCache/NetBridgeSpoof.cs, it should set the value of the cache item and return null if an existing value is not found.  Otherwise, it won't work with .net standard 2.0:

```
                public object AddOrGetExisting( string key , object value , CacheItemPolicy policy )
		{
			object result;
			if (this.TryGetValue(key, out result)) {
			     return result;
			}
			else {
			     this.Set(key, value);
			     return null;
			}
		}

```

**Comment by GeekActual** [comment]
@johnhamm:
are you sure about that return null? since it is a AddOrGetExisting, think you mean to have it as follows

```
                public object AddOrGetExisting( string key , object value , CacheItemPolicy policy )
		{
			object result;
			if (this.TryGetValue(key, out result)) {
			     return result;
			}
			else {
			     this.Set(key, value);
			     return value;
			}
		}
```

**Comment by GeekActual** [comment]
Damn, didn't mean to close it.

**Comment by johnhamm** [comment]
Yeah I also think it's odd that AddOrGetExisting returns null when an existing value isn't in the cache, but that's Microsoft's behavior so your NetBridgeSpoof class should as well so there aren't any side effects.

Besides, the CachingService checks to see if it is null when a new value is added, and returns the inserted value if that is the case:
https://github.com/jornj/LazyCache/blob/c1d8b105404b1483983778cffdf67282f560ca5f/LazyCache/CachingService.cs#L105

Microsoft's reference:
https://msdn.microsoft.com/en-us/library/dd988741(v=vs.110).aspx
"If the cache does not have a cache entry whose key matches the key parameter, a new cache entry is created, and the MemoryCache.AddOrGetExisting method overload returns null. If a matching cache entry exists, the existing entry is returned."

**Comment by GeekActual** [comment]
well color me embarrassed! I was thinking of CachingService's `GetOrAdd<T>` and just "assumed" MS did the same thing... helps if you RTFM.. thanks for catching that John.

**Comment by Braed** [comment]
Using the alpha package from @johnhamm's feed with .NET Core 2.0 and it appears as though caching isn't working. ObjectCache count isn't increasing and the lambda is being executed every time. Not sure what other information I can give you (relatively new to .net). Using DI:  
`result.RelatedPosts = _cachingService.GetOrAdd($"relatedPostsForPostId-{postId}", () => _postsRepository.GetRelatedPosts(post, relatedPostsPageLength).ToList());`

**Comment by GeekActual** [comment]
Hey Braed,

I assume you are using .Net Core 2.0 (ASP.NET Core 2.0)?  Can you offer a copy of the code that doesn’t appear to be working?

What does the GetRelatedPosts code look like?

Matthew
ACME AtronOmatic, LLC.

**Comment by Braed** [comment]
[Here's a DotNetFiddle of GetRelatedPosts.](https://dotnetfiddle.net/ySv7kr)
This method is to fetch related posts and sort them based on match percentage for a blog API.
I'm not confident in my C# code so if you see anything horrific, please let me know lol

**Comment by Jeffroiscool** [comment]
I seem to experience the same issue.

https://dotnetfiddle.net/Q6cqxs Code where I try to implement this.
Function: https://dotnetfiddle.net/B0hu7W

**Comment by johnhamm** [comment]
I'll update the feed with the latest buildwhen I get home and see if that changes anything.

**Comment by Jeffroiscool** [comment]
Please let us know when you did, would love to try it out!

**Comment by Jeffroiscool** [comment]
Updated but still it's not caching: https://i.imgur.com/CxJrObB.png

**Comment by johnhamm** [comment]
All the unit tests passed.  When I create a simple app.net core app, it caches.  Can you upload a project?

**Comment by Jeffroiscool** [comment]
I just uploaded my project to github (was a bit lazy before not uploading it yet :D)
Here's the file that should do the caching. 

https://github.com/Jeffroiscool/AnimeFlix/blob/master/AnimeFlix/Pages/Anime.cshtml.cs

**Comment by johnhamm** [comment]
I am getting a cache entry when I try it on your project:
https://imgur.com/a/snSIm

**Comment by Jeffroiscool** [comment]
Strange, what did you change? Did you actually try it in the page model?

**Comment by bhedia** [comment]
Any movement on this? I would like to take advantage of this package in netstandard2.0 as well.

**Comment by Jeffroiscool** [comment]
Sorry for the lack of feedback, I had a smarter friend look for me and he made this commit to my program to get it working: https://github.com/Jeffroiscool/AnimeFlix/commit/5bf02f7651135a95219c9af6209ed22742881daf

And that's with using this version of Lazycache: https://www.myget.org/F/lazycache/api/v3/index.json

**Comment by alastairtree** [comment]
I have started work on this, but have taken a slightly different approach to that of this fork, but the basics are now working. I decided to target netstandard 2 (and not do multi targeting) and there are a number of breaking changes so this will be a major bump to version 2.0. Feel free to check out https://github.com/alastairtree/LazyCache/tree/feat/netcore2 if you are keen. Any feedback is welcome, and let me know if you think the breaking changes are unreasonable - I hope they should be very quick to fix.

**Comment by alastairtree** [comment]
There is now a beta version of LazyCache 2.0 for netstandard 2 on nuget.org. Feedback most welcome.

```
dotnet add package LazyCache --version 2.0.0-beta01
```
In addition there are a set of dependency injection bindings available:

```
dotnet add package LazyCache.AspNetCore --version 2.0.0-beta01
```

**Comment by alastairtree** [comment]
I expect to release version 2 soon (already out in pre release) and as no-one is shouting for a multi targeted net45/46 version I feel I can close this issue for the alternative fork. Please shout if you disagree.
