### ISSUE TITLE
.NETCore 2.0 Support?

### ISSUE THREAD

**Issue by xplatsolutions** [alastairtree/LazyCache#26]
I saw the previous post but I couldn't find if eventually there is a code branch or -pre nuget regarding .NET Core 2.0 support, any update?

Thank you for the library, works amazingly nice!

**Comment by jpmckearin** [comment]
https://github.com/alastairtree/LazyCache/issues/24

**Comment by RealDotNetDave** [comment]
+1

**Comment by alastairtree** [comment]
Duplicate of #24

**Comment by alastairtree** [comment]
There is now a pre release net standard version on Nugent.org. Let me know what you think.
