### ISSUE TITLE
Question How to update an item in a cache where a value is a list of object

### ISSUE THREAD

**Issue by simba22042** [alastairtree/LazyCache#27]
How do I go about updating a particular object in cached object with a given key. 

Here is an example 

   cache.GetOrAdd("latest-products", () => oProductService.GetProducts(), policy); 

I am populating a list of product to "latest-products" and want to update a particular product in the given list and then update the cache. 

oProductService.GetProducts() returns a list of Products

public class Products
    {
        public Guid Id {get;set;}
        public string Name { get; set; }

         public int Quantity { get; set; }
    }

**Comment by jornj** [comment]
I assume you could do something like 
```c#
cache.GetOrAdd("latest-products", () => oProductService.UpdateProduct(newValue), policy);
```

**Comment by alastairtree** [comment]
As @jornj  said, just `Add(...)` the updated list to the cache to ensure it is cached. See [this section](https://github.com/alastairtree/LazyCache/wiki/1.0-LazyCache-API-documentation#add-an-item-to-the-cache-manually-for-the-default-duration-20-mins) of the docs for more info.

**Comment by simba22042** [comment]
Sorry guys I still not get an item in a cached list to update. 

So basically I have cached a list of objects using a key but now I am trying to update a particular object in a list and somehow object is not getting updated. 

So oProductService.GetProducts() has an item in the list with an Id of  278E4538-0F40-4220-9F05-3AFCD532BE01 but once in cache I want to update it at some point. I have tried using the code below but does not seem to update the product with id 278E4538-0F40-4220-9F05-3AFCD532BE01.

Here is what I have.

var policy = new CacheItemPolicy()
            {
                Priority = CacheItemPriority.NotRemovable,
                AbsoluteExpiration = DateTime.UtcNow.AddSeconds(5000),
                RemovedCallback = OnCacheExpired,
            };

            cache.GetOrAdd("latest-products", () => oProductService.GetProducts(), policy);



            var items = cache.Get<List<Products>>("latest-products");
            Products product = new Products { Id = new Guid("278E4538-0F40-4220-9F05-3AFCD532BE01"), 
           Name = "Update Quqntity", Quantity = 10 };
            cache.GetOrAdd("latest-products", () => product);

**Comment by simba22042** [comment]
I will be using SQL Dependency to get an update on an item but then do not want to call GetProducts again just want to update a particular item in the list that is because GetProducts is very slow and expensive operation.

**Comment by alastairtree** [comment]
Have you tried recreating the list of products when it needs updating by creating a new list based on all the old items except the one updated item plus the new version of the updated item, and then calling `Add(..)` to put that into the cache? GetOrAdd() wil never add to the cache if the key is already cached.

**Comment by jornj** [comment]
@simba22042 , as @alastairtree mentioned, GetOrAdd will not add if it already exists. And in your code example, you do just that. Try replacing the last cache.GetOrAdd with a cache.Add.
