### ISSUE TITLE
Handling long running cache population functions

### ISSUE THREAD

**Issue by jfrueh** [alastairtree/LazyCache#28]
Great library!  I'm looking to solve this use case:

1. There is an item in the cache that has expired  
2. This cache item is now requested again but it takes 30 seconds to retrieve data from the db.
3.  App just spins on all requests needing this cache item as it waits for the update to complete.

Rather than have the thread lock and block the app, I'd rather return the "expired" item and then when the new item is retrieved and available of course that can be returned.   Essentially the only time there would be a true block where the user waits would be on the initial cache load.

Is there a good way to handle this?  Can the RemovedCallback be utilized for something like this?

Thanks for any help or direction you can provide.

**Comment by alastairtree** [comment]
I can think of a couple of ways:
* Say you set the cache item to absolutely expire every 30m. Add a timer to that tick every 29m, and on tick you add the new item to the cache. That way the cache is regularly refreshed and you are never really waiting for it to refresh.
* Alternatively you could cache the item twice, with the second entry having a much longer expiry. if the first entry is not available you fetch from the second entry, and then trigger a background task to repopulate both entries ready for the next request. the problem with this method is that it has an obvious race condition and could end up generating it more than once. You probably need to wrap this behavior in some locking

**Comment by jfrueh** [comment]
Will go with idea 1, that seems like a logical approach.  I wasn't sure if something like was built in or not so that's why I asked, but it will be easy enough to implement. Thanks for your response and this library.  It's really simplified caching for us.
