### ISSUE TITLE
Proper IDisposable support in CachingService

### ISSUE THREAD

**Issue by ghen** [alastairtree/LazyCache#29]
**CachingService** class cerates **ICacheProvider** instance silently in constructor. The last one supports **IDisposable**.

Expected **CachingService** to be disposable (e.g. implement **IDisposable**) too in order to dispose internal resources properly.

**Comment by alastairtree** [comment]
Hmmmm. Good question. Yes technically you are correct - it can create an instance that should be disposed, but to be clear it creates exactly one global static instance `CachingService.DefaultCacheProvider` and does so only if you use the default constructor. 

Really that constructor is there to maintain compatibility with older pre dot net core style users who are not using dependency injection - it mimics the old version's default constructor that referenced the global default cache instance of Runtime.Caching.MemoryCache. If you use Microsoft.Extensions.DependencyInjection, [LazyCache.AspNetCore](https://github.com/alastairtree/LazyCache/blob/feat/netcore2/LazyCache.AspNetCore/LazyCacheServiceCollectionExtensions.cs) and the `AddLazyCache()` method in DI startup then that constructor is never used and so nothing would ever need to be disposed. Perhaps a better solution would be to obsolete that constructor and the default property? In normal usage it does not need to be disposed, and seems overkill to make all instances disposable for a single instance of the provider you may not be using.

**Comment by ghen** [comment]
Thanks for the explanation. Marking it as Obsolete sounds like a valid idea.

It just this logic was not so obvious from the constructor signature 😊.

 

Sincerely,

Eugene

**Comment by alastairtree** [comment]
@bradley-varol  - that is an error from Entity Framework, not lazy cache. Probably your cache delegate is running a query on a DataContext too late, after it has been disposed.  Or maybe you need to await the async query before disposing the content.

**Comment by bradley-varol** [comment]
I don't fully understand your answer. The query is not asynchronous, and the exception is only thrown on the second use of the same key (accessing cache, not the delegate).

Here is some sudo code of what i'm doing (both _cache and _postsRepository are DI):
`var posts = _cache.GetOrAdd("Posts", () => _postsRepository.GetPosts());`

If i do `var posts = _postsRepository.GetPost();` I have no issues.

**Comment by bradley-varol** [comment]
Okay, this is not related to my related entities. I've removed my Include() and my Foreign Keys.

**Comment by alastairtree** [comment]
`.Include()` is eager loading, rather than lazy. Try adding `AsNoTracking()` to stop the entities holding a connection to the DbContext

**Comment by bradley-varol** [comment]
I'd like to Eager load these entities though. Thanks!

**Comment by alastairtree** [comment]
@ghen I have now fixed the creating of disposable provider in the default constructor by marking it obsolete as discussed. Will close this issue now.
