### ISSUE TITLE
Add restricted sliding expiration policy

### ISSUE THREAD

**Issue by roryprimrose** [alastairtree/LazyCache#34]
Thank you for creating this package, it looks great.

One of the features I'd like to see is a restricted sliding expiration policy which is really just a combination of absolute and sliding expirations. 

I've written a few systems that benefit from this because most of the work is done within the sliding expiration, but if the data usage remains hot, there is no eviction from the cache. Absolute expiration is not always appropriate either because you don't get the advantage of releasing memory if it is not used (sliding).

Thoughts?

**Comment by alastairtree** [comment]
I can see how such a feature seems elegant, but in practise I find that just using absolute expiry works fine for me as I rarely get sufficient memory pressure to warrant the premature eviction of items in the cache. Seeing as it is not implemented in System.Runtime.Caching anyway it would be significant effort to add it to LazyCache version 0.7 and personally i can'y commit time to building it for an old version of the library.

In the dotnet standard 2 version (in beta) we depend on Microsft.Extensions.Caching.Memory and that already has the feature implemented as you descibe, have a look at https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycacheentryoptions.slidingexpiration 
 
> (s;iding expiration) will not extend the entry lifetime beyond the absolute expiration (if set).

So to get that behaviour you just need to setup a MemoryCacheEntryOptions with both sliding and absolute, and voila!

Hope that helps?
