### ISSUE TITLE
Auto key generation based on expression tree

### ISSUE THREAD

**Issue by AsValeO** [alastairtree/LazyCache#37]
Hi @alastairtree ,
LazyCache is a great library and I gonna use it all the time. Thank you!
Can you implement an auto key generation based on expression tree? For Async version too.

**Comment by alastairtree** [comment]
Have a look at the code i shared in #36 as i think this would generate geys automatically based on the type? You could then add this to your app as an extension method and would not need to be built into LazyCache.

**Comment by alastairtree** [comment]
Sorry, looks like I have not been able to help. Closing as no response, but please @ reference me and I will re-open if needs be. Thanks.
