### ISSUE TITLE
LazyCache with asp.net core 2.0 targeting version 4.61

### ISSUE THREAD

**Issue by simba22042** [alastairtree/LazyCache#39]
Is there a way to use LazyCache 2 with asp.net core 2.0 targeting version 4.6.1

**Comment by simba22042** [comment]
Anyone can assist?

**Comment by alastairtree** [comment]
Hi. LazyCache 2.0 targets netstandard 2, which is supported on both core and full framework at 4.6.1 or above. Was there a particular problem you were having?

**Comment by alastairtree** [comment]
Sorry, looks like I have not been able to help. Closing as no response, but please @ reference me and I will re-open if needs be. Thanks.
