### ISSUE TITLE
Support dot net core

### ISSUE THREAD

**Issue by alastairtree** [alastairtree/LazyCache#4]
Should we change our dependency on to M[icrosoft.Framework.Caching.Memory](https://www.nuget.org/packages/Microsoft.Framework.Caching.Memory/)?

When dotnet core 2.1 releases a backwards compat version of system.runtime.caching will be available for netcore. It is available as prerelease now, see https://github.com/dotnet/corefx/issues/14529

**Comment by burnchar** [comment]
.NET Core and full .NET are likely to be used alongside each-other for years.
Is it practical to support both caching methods?

**Comment by artstalker** [comment]
What about .net core support? Are you going to release dot net core version of this product?

**Comment by Nucs** [comment]
+1

**Comment by bbrandt** [comment]
The library to depend on now seems to be [Microsoft.Extensions.Caching.Memory](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/) which is a .NETStandard 1.3 and .NETFramework 4.5.1 library.

**Comment by alastairtree** [comment]
Agree we want to make this netstandard at this point, and 1.3 would be a good place to aim for. Also worth looking at the memory/distributed options in dotnetcore as these also have nicer APIs than the old .net4 ones. See 
https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.extensions.caching.memory
https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.extensions.caching.distributed

**Comment by PureKrome** [comment]
Any news on this?

**Comment by Tersken** [comment]
Any news?

**Comment by GeekActual** [comment]
I have a working version that is multi-targeted to net45, net46, and netstandard2.0 see #24

**Comment by alastairtree** [comment]
I have started work on this, and the basics are now working. Decided to target netstandard 2 and there are a number of breaking changes so this will be a major bump to version 2.0. Feel free to check out https://github.com/alastairtree/LazyCache/tree/feat/netcore2 if you are keen.

**Comment by alastairtree** [comment]
There is now a beta version of LazyCache 2.0 for netstandard 2 on nuget.org. Feedback most welcome.

```
dotnet add package LazyCache --version 2.0.0-beta01
```
In addition there are a set of dependency injection bindings available:

```
dotnet add package LazyCache.AspNetCore --version 2.0.0-beta01
```

**Comment by alastairtree** [comment]
Version 2.0.0-beta02 has been released to nuget.org with some minor refactorings and a new GetOrAdd method that allows the cache item factory/lamda define the cache duration/expiry at execution time rather than in advance, see #5 for an example.

**Comment by lookingcloudy** [comment]
Great - it looks like the beta version works with .Net Core 2.0.

**Comment by AugustoDeveloper** [comment]
It's very nice version, i'm using and it's so much fast.

**Comment by GeekActual** [comment]
Well done @alastairtree , hope my little contribution helped, we are converting over to use your "official" LazyCache in our core library (replacing my temp one).

**Comment by TrevorVonSeggern** [comment]
Are there any blockers for this issue to get resolved?

btw, great work on this!

**Comment by alastairtree** [comment]
Just published a final beta (3). Assuming no-one has any issues I can release in a few days. Also need to finish updating the docs to version 2.0. For those upgrading from version 0.7 I have added some upgrade docs at https://github.com/alastairtree/LazyCache/wiki/upgrade-to-2

**Comment by avikenjale** [comment]
Any idea by when can LazyCache.AspNetCore 2.0.0 final version release? Due to some reason, I am not allowed to use beta.

**Comment by bradbamford** [comment]
Final beta (3)  was published in May (to be released in a days).  Is there any reason that release didn't happen?

**Comment by agltestshr** [comment]
Would love to know when the final version will be released. 
I'm unfortunately not allowed to use the beta version. Thanks!

**Comment by alastairtree** [comment]
Quick note to say docs are updated, last few tweaks completed and final version 2.0.0 has been released to nuget.org. Sorry it took so long!

**Comment by burnchar** [comment]
Thank you for your efforts!
