### ISSUE TITLE
How to persist the cache object between application reboots?

### ISSUE THREAD

**Issue by beppe9000** [alastairtree/LazyCache#40]
Is there a serialization method available or do I have to use the default serializers ?

**Comment by alastairtree** [comment]
MemoryCache does not support serialisation, It is only designed for in memory caching. You would be best placed to look at IDistructuredCache rather than lazycache, see https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2
