### ISSUE TITLE
How to configure default expiry time in v2.0?

### ISSUE THREAD

**Issue by arisliang** [alastairtree/LazyCache#41]
Like in prior version,

// Change the default cache duration from 20 minutes to 3 minutes
var cache = new CachingService() { DefaultCacheDuration= 60 * 3 };

Now v2.0 favors DI, that means it doesn't create new instance manually like above anymore.

It's probably somewhere in the doc, but I couldn't find it yet.

**Comment by alastairtree** [comment]
Sorry, docs not up to date yet. Try this to chage the default to 3m.

```csharp
  IAppCache cache = new CachingService(CachingService.DefaultCacheProvider);
  cache.DefaultCachePolicy.DefaultCacheDurationSeconds = 60 * 3; //3mins
```

**Comment by LiamKarlMitchell** [comment]
https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#configuring-the-default-cache-duration-of-20-minutes
Wiki needs update also..

```csharp
var cache = new CachingService() { DefaultCachePolicy.DefaultCacheDurationSeconds = 60 * 3; };
```

How to set sliding as default?

**Comment by rozbo** [comment]
> https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#configuring-the-default-cache-duration-of-20-minutes
> Wiki needs update also..
> 
> ```cs
> var cache = new CachingService() { DefaultCachePolicy.DefaultCacheDurationSeconds = 60 * 3; };
> ```
> 
> How to set sliding as default?

default is 1200s

```c#
namespace LazyCache
{
  public class CacheDefaults
  {
    public virtual int DefaultCacheDurationSeconds { get; set; } = 1200;

    internal MemoryCacheEntryOptions BuildOptions() => new MemoryCacheEntryOptions()
    {
      AbsoluteExpiration = new DateTimeOffset?(DateTimeOffset.UtcNow.AddSeconds((double) this.DefaultCacheDurationSeconds))
    };
  }
}
```
