### ISSUE TITLE
Implement ExpirationToken for Sliding expiration

### ISSUE THREAD

**Issue by AsValeO** [alastairtree/LazyCache#42]
Please, implement a `ExpirationToken` for sliding expiration feature like for standard `MemoryCache`:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/primitives/change-tokens?view=aspnetcore-2.1

**Comment by alastairtree** [comment]
Would the `MemoryCacheEntryOptions.RegisterPostEvictionCallback(...)` method that is already supported fulfill your needs (as that already allows you to get notified on cache eviction)?

**Comment by alastairtree** [comment]
Sorry, looks like I have not been able to help. Closing as no response, but please @ reference me and I will re-open if needs be. Thanks.

**Comment by AsValeO** [comment]
This helped. Thank you.
