### ISSUE TITLE
How to use redis instead of memory cache?

### ISSUE THREAD

**Issue by nbulusanjr** [alastairtree/LazyCache#47]

**Comment by alastairtree** [comment]
In which version of lazy cache?

**Comment by alastairtree** [comment]
The docs are admitedly a little scarce but have a look at https://github.com/alastairtree/LazyCache/wiki/2.0-Extending-LazyCache-with-Redis,-Cassandra-etc

You need to pass in a redis backed version of ObjectCache, something like https://github.com/justinfinch/Redis-Object-Cache.

If possible though I would consider using IDistributedCache from MS which is .netstandard2 compatible, and skipping LazyCache. The docs for this are at https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2

**Comment by replaysMike** [comment]
This is a little old, but isn't LazyCache only accepting an ICacheProvider?
