### ISSUE TITLE
Unable to resolve service for type 'LazyCache.IAppCache'

### ISSUE THREAD

**Issue by sukhoi1** [alastairtree/LazyCache#51]
Unable to resolve service for type 'LazyCache.IAppCache' there is no service.[register] method in beta3.

**Comment by alastairtree** [comment]
If you are using Microsoft.Extensions.DependencyInjection you need to install LazyCache.AspNetCore and then you can register all LazyCache depenndencies using `serviceCollection.AddLazyCache()`. Source code is at https://github.com/alastairtree/LazyCache/blob/feat/netcore2/LazyCache.AspNetCore/LazyCacheServiceCollectionExtensions.cs

Does that help? If not can you give me a little more detail. Thanks.

**Comment by alastairtree** [comment]
Sorry, looks like I have not been able to help. Closing as no response, but please @ reference me and I will re-open if needs be. Thanks.
