### ISSUE TITLE
LazyCache 2.0.0-beta03 Can be used in .net framework 4.6 + ????

### ISSUE THREAD

**Issue by neozhu** [alastairtree/LazyCache#54]
Exception of type 'Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy+InvalidRegistrationException' was thrown.

container.RegisterType<IMemoryCache, Microsoft.Extensions.Caching.Memory.MemoryCache>(new ContainerControlledLifetimeManager());
            container.RegisterType<ICacheProvider, LazyCache.Providers.MemoryCacheProvider>(new ContainerControlledLifetimeManager(), new InjectionConstructor(typeof(IMemoryCache)));
            container.RegisterType<IAppCache, CachingService>(new ContainerControlledLifetimeManager(), new InjectionConstructor(typeof(Lazy<ICacheProvider>)));

**Comment by alastairtree** [comment]
Hi @neozhu, I haven't used Unity but the basic code you have shown may not be right. I think you want to change the registration for CachingService to something like:

`container.RegisterType<IAppCache, CachingService>(new ContainerControlledLifetimeManager(), new InjectionConstructor(typeof(Lazy<ICacheProvider>)));`

Also compare to what we do for the microsoft dependency injection framework - see https://github.com/alastairtree/LazyCache/blob/feat/netcore2/LazyCache.AspNetCore/LazyCacheServiceCollectionExtensions.cs

You can definately use 2.0 with 4.6.1, but 4.6 does not support netstandard 2, see https://docs.microsoft.com/en-us/dotnet/standard/net-standard.

**Comment by neozhu** [comment]
I have already got it.thank you
