### ISSUE TITLE
Can you consider an addorupdate(key,()=>{}) method?

### ISSUE THREAD

**Issue by neozhu** [alastairtree/LazyCache#55]
Can you consider an addorupdate(key,()=>{}) method?

**Comment by greigs** [comment]
Anonymous functions work fine already (at least they work for me in LazyCache.2.0.0-beta03).

**Comment by neozhu** [comment]
for dotnet 4.6/4.8 Will update & release new version?

**Comment by alastairtree** [comment]
Yeah this works fine for the 2.0 version that is in beta already i think so will close for now.
