### ISSUE TITLE
AppCacheExtenions

### ISSUE THREAD

**Issue by JohnL404** [alastairtree/LazyCache#64]
This is pretty trivial so I apologize but I think the new AppCacheExtenions class should be called AppCacheExten**s**ions?  Thanks!

**Comment by alastairtree** [comment]
Thank you - and sorry my spelling is often terrible! Pretty sure you are not wrong. Feel free to submit a quick PR for it or i'll correct next time I work on it.

**Comment by JohnL404** [comment]
I'd created a branch locally with the correction but it's not letting me push it to GitHub in order to submit a PR (getting a 403).  I'm new to GitHub as a contributor - is there a different process I should be following to create my branch?

**Comment by alastairtree** [comment]
To submit a PR fork the repo, then create a branch on that repo. When you
are happy create a Pull Request into LazyCache for me to review. See
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork.

**Comment by JohnL404** [comment]
Will do - thanks a ton!

**Comment by alastairtree** [comment]
Awesome, thanks.

![image](https://user-images.githubusercontent.com/6273429/55085436-949eca00-509e-11e9-904d-59dac43280dc.png)
