### ISSUE TITLE
Caches task with data instead of data

### ISSUE THREAD

**Issue by vhatsura** [alastairtree/LazyCache#68]
Hey, @alastairtree!

Thanks for the great library. I had a chance to look into codebase and found out that when we call GetOrAddAsync, library caches Task with data instead of data. As I see, this behavior is caused by the following code:
https://github.com/alastairtree/LazyCache/blob/ddb48e07ffaf7d561fcaef7e8d5db8178540697d/LazyCache/CachingService.cs#L127-L143
Is it expected  behavior to call synchronous version of `GetOrCreate` in asynchronous version or it's an issue?

**Comment by alastairtree** [comment]
Yeah it's by design, not a typo, because we actually cache the AsyncLazy and then await the result of that, rather than cache the async delegate directly. But always open to suggestions or bug reports.

**Comment by vhatsura** [comment]
Ohh, got it. Thanks for clarification. Another small question: is it make sense to check cached value on null? I know that sometimes is useful to cache null value as marker of no data, but, first of all, it seems that rare case and also I prefer to use custom object with no data marker. What is your thoughts, @alastairtree?

**Comment by alastairtree** [comment]
Yeah as you say I have seen people caching null deliberately as a marker so it would be a breaking change to reject null, hence not having changed it. It's daft but not dangerous so have been happy to leave it be so far! Could be a change for v3 if people felt strongly about it as it is a bit of an anti pattern.

**Comment by vhatsura** [comment]
Thanks for reply!)
