### ISSUE TITLE
Lazycache 2.0.1 not able to install on aspnetcore 2.1

### ISSUE THREAD

**Issue by arisliang** [alastairtree/LazyCache#71]
Currently 2.0.1 requires Microsoft.Extensions.Cachcing.Abstractions >=2.2.0, this requires aspnetcore 2.2. So aspnetcore 2.1 is not able to install Lazycache 2.0.1

Error details:
`
NU1107	Version conflict detected for microsoft.extensions.caching.abstractions. Install/reference Microsoft.Extensions.Caching.Abstractions 2.2.0 directly to project  to resolve this issue. 
  -> LazyCache 2.0.1 -> Microsoft.Extensions.Caching.Abstractions (>= 2.2.0) 
  -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Caching.Abstractions (>= 2.1.1 && < 2.2.0)	
`

**Comment by alastairtree** [comment]
What happens if you install Microsoft.Extensions.Caching.Abstractions 2.2.0 directly into your project? This that will resolve the issue?

If not, I could change LazyCache to use a floating dependency like below, but not sure on all the possible impacts that might have on our many users so will need some testing

    <PackageReference Include="microsoft.extensions.caching.abstractions" Version="2.*" />
    <PackageReference Include="microsoft.extensions.caching.memory" Version="2.*" />

**Comment by arisliang** [comment]
Same error after copying the above two line into the project file. It still detects the version conflict. Seems even though specify 2.*, aspnetcore 2.1.1 still requires to stick to lower version.

**Comment by alastairtree** [comment]
What happens if you install Microsoft.Extensions.Caching.Abstractions 2.2.0 directly into your project? Think that will resolve the issue?

(Those PackageReference lines were possible changes for the LazyCache library to resolve the issue - not for your project!)

**Comment by RubberChickenParadise** [comment]
@alastairtree when using an asp.net core web app the on .net core 2.1 there is the Microsoft.AspNetCore.App SDK dependency which depends on Microsoft.Extensions.Caching.Abstractions versions >= 2.1.0 and < 2.2.0.  This prevents Microsoft.Extensions.Caching.Abstractions 2.2.0 from being installed directly.

The suggestion would be to require >= 2.1.0 and < 2.2.0 for .net core 2.1.

I should have some time tonight to make the change and open a pull request for the package references after some testing.

(I am currently running into this so its fresh in my head.)

**Comment by arisliang** [comment]
From another point of view, v2.0.0-beta3 requires `microsoft.extensions.caching.memory (>= 2.0.0)` and `microsoft.extensions.caching.abstractions (>= 2.0.0)`. While moving to v2.0.0, both dependencies becomes >=2.2.0.

So it is a breaking change between v2.0.0-beta3 to v2.0.0.

**Comment by netmajor** [comment]
I am also waiting for this fix for package. Now I am unable to use LazyCashe in .net core 2.1 :(

**Comment by alastairtree** [comment]
This will be fixed in a the next release 2.0.2 and LazyCache will go back to depending on the 2.1.0 set of framework libraries so we are aligned with the core LTS support policy. Thanks for getting in touch, and sorry it took a while to getting round to fixing this,
