### ISSUE TITLE
Add support and docs for async cachable delegates

### ISSUE THREAD

**Issue by alastairtree** [alastairtree/LazyCache#8]

**Comment by jxmiller** [comment]
I second this... perhaps?
This compiles:
`var result = cache.GetOrAdd("Key", async () => await DbContext.Database.ExecuteStoredProcedureAsync<MyClass>(paramObj, ProcName));`

But then it hangs forever.

**Comment by alastairtree** [comment]
Yeah, ideally we would have GetOrAddAsync methods supporting async/tasks. Will have a look when I get some time.

**Comment by alastairtree** [comment]
I have made good progress on this and have a working version. See #9 

I would appreciate someone to try it out or review the code? Package available for testing from the [appveyor build artefacts](https://ci.appveyor.com/api/buildjobs/ijbauc8x1g9lnvcj/artifacts/LazyCache%2Fbin%2FRelease%2FLazyCache.0.7.0.12.nupkg)

**Comment by alastairtree** [comment]
LazyCache 0.7 now support async/task based caching.
