### ISSUE TITLE
Is there a way to cache in item forever ?

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [alastairtree/LazyCache#81]
Hi,

this is a very simple question indeed. 

I would like to know if there is a built in way to cache an item forever (the cached item never expires, so it is never removed from the cache).
 
Is there a way to specify a never expiring item when it is added to the cache or the only way to do so is setting a very long absolute expiration (something like `DateTimeOffset.Now.AddYears(1)`) ?

Thanks for helping

**Comment by DaveInCaz** [comment]
I think this is described in the [API docs section](https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#custom-cache-policies) "Custom cache policies", where it shows in part:

```
var options = new MemoryCacheEntryOptions(){ 
   Priority = CacheItemPriority.NotRemovable
};
```

Dave

**Comment by EnricoMassoneDeltatre** [comment]
> I think this is described in the [API docs section](https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#custom-cache-policies) "Custom cache policies", where it shows in part:
> 
> ```
> var options = new MemoryCacheEntryOptions(){ 
>    Priority = CacheItemPriority.NotRemovable
> };
> ```
> 
> Dave

I agree with you. 

To summarize, the trick to cache an item forever is calling one of the methods of `IAppCache` allowing you to pass an instance of `MemoryCacheEntryOptions`. 

In order to cache the item forever you have to do two things on the `MemoryCacheEntryOptions` instance: 

- **do NOT set** any property allowing you to control the expiration of the cache entry itself (properties like `AbsoluteExpiration` or `SlidingExpiration`). Just leave all of these properties to their default values.
-  **do set** the property `Priority` to the value `NeverRemove` of the `CacheItemPriority` enumeration. This must be done in order to be sure that even if the [Compact method](https://github.com/aspnet/Extensions/blob/0040eaca278f18962e982b7e3d25cd7dc957e745/src/Caching/Memory/src/MemoryCache.cs#L389) is called, then the cache item won't be removed from the cache.

Please notice that the [Compact method](https://github.com/aspnet/Extensions/blob/0040eaca278f18962e982b7e3d25cd7dc957e745/src/Caching/Memory/src/MemoryCache.cs#L389) is meant to be called by the developer, based on what I know it is never called automatically by the internals of the ASP.NET core MemoryCache as you can verify from this issue (https://github.com/aspnet/AspNetCore.Docs/issues/11216). This is true regardless of a `SizeLimit` has been set on the `MemoryCache` instance.
