### ISSUE TITLE
Question about depending on v2.2.0 of Microsoft.Extensions.* libraries

### ISSUE THREAD

**Issue by TheBlueSky** [alastairtree/LazyCache#83]
What is the reason for depending on v2.2.0 for `Microsoft.Extensions.Caching.Abstractions` and `Microsoft.Extensions.Caching.Memory` instead of `2.1.x`?

I am asking because ASP.NET Core 2.1.x is an LTS release, which means people will continue using it for at least couple of years more (if not longer) and this in turn means that if they are using LazyCache with their ASP.NET Core 2.1 application, they will receive a warning that ASP.NET Core depends on v2.1.x of the libraries while the resolved version is 2.2.x.

**Comment by alastairtree** [comment]
This will be fixed in a the next release 2.0.2 and LazyCache will go back to depending on the 2.1.0 set of framework libraries so we are aligned with the core LTS support policy. Thanks for getting in touch, and sorry it took a while to getting round to fixing this,
