### ISSUE TITLE
Copying the cached Item

### ISSUE THREAD

**Issue by IamChandanKumar** [alastairtree/LazyCache#90]
I want to copy one of the cached data into the cache itself with different key.

Is it possible to achieve directly into the cache or do we need to first get the cached data and then create another Cached item with another key?

**Comment by alastairtree** [comment]
In memory caching is based on object references so if you were to put the same object into the cache with two different keys you would have two references to the same object. If you want to copy the object you would be best to make the object cloneable and then clone the object in the cache, and cache the clone with a second cache key.
Hope that helps.
