### ISSUE TITLE
AddExpirationToken with CancellationChangeToken is not being honored

### ISSUE THREAD

**Issue by ddanielorlano** [alastairtree/LazyCache#96]
I'm trying to expire and evict a Cache Entry using a CancellationChangeToken. I am not seeing the Token expiration being honored, until I make another call to GetOrAddAsync.
As referenced [here ](https://github.com/aspnet/Caching/issues/248#issuecomment-258571802)

With IMemoryCache I am seeing the entry expire
```
    
            var result = await _memCache.GetOrCreateAsync(CacheKey, entry =>
                {

                    var expireToken = new CancellationChangeToken(new CancellationTokenSource(10000).Token);

                    var options = new MemoryCacheEntryOptions();

                    options.SetPriority(CacheItemPriority.NeverRemove);
                    options.AddExpirationToken(expireToken);
                    options.RegisterPostEvictionCallback(callback: MyPostEvictionCall, state: this);

                    entry.SetOptions(options);

                    return _mySvc.BuildMyCacheEntry();

                }).ConfigureAwait(false);
```
I see the call back hit after 10 seconds with this log
````
        private void MyPostEvictionCall(object key, object value, EvictionReason reason, object state)
        {
            Logger.Info("!POST EVICTION!");
        }
````
When I switch to LazyCache
`  var result = await _lazyCache.GetOrAddAsync(CacheKey, entry =>`
The callback is not hit until I send another request

The logs indicate that first `_mySvc.BuildMyCacheEntry();` is hit, then **"!POST EVICTION!"**

**Comment by alastairtree** [comment]
Thanks for the bug report. I think this might be the same issue as #84 to do with the order on which we set values on the cache entry which is not that easy to fix.

**Comment by alastairtree** [comment]
Version 2.1.0 has some changes that will support this. You need to pass the expiration change token with the options so that it can be evaluated outside the lazily evaluated func. like this:

```
var tokenSource = new CancellationTokenSource(someNumberOfMS);
            var expireToken = new CancellationChangeToken(tokenSource.Token);
            var result = cache.GetOrAdd("someKey",
            entry =>
            {
                entry.RegisterPostEvictionCallback((key, value, reason, state) => Console.WriteLine("cache item removed!!"));
                return new SomeThingHere();
            }, new MemoryCacheEntryOptions().AddExpirationToken(expireToken));

``
In addition there is a new set of helpers to make this feature much easier so you do not need to use the cancellation tokens yourself and can just ask for immediate expiration insteas of lazy expiration. Note that ImmediateExpiration uses more resources (timers under the hood with the CancellatonTokenSource):

```
var result= await cache.GetOrAddAsync(
    "someKey", 
    () =>GetStuff(), 
    DateTimeOffset.UtcNow.AddSeconds(100), 
    ExpirationMode.ImmediateExpiration);
``

**Comment by Dedme** [comment]
i was just chasing this in 2.0.4, thinking i was going mad. perfect timing!
