### ISSUE TITLE
NullReferenceException thrown in MockCachingService

### ISSUE THREAD

**Issue by DavidRogersDev** [alastairtree/LazyCache#97]
I'm using the MockCachingService in a unit test. The relevant code being tested looks like this (I'm trying to keep it brief, but can give more details if required):  

```
var cacheKey = string.Concat(CacheKeys.FacilityForCarpsUrl, _currentUser.CurrentFacilityId);
facility = _appCache.GetOrAdd(cacheKey, () => _appUserService.GetFacilityAdminDto(userLoginDto.PrimaryFacilityID.Value));  
```
  
So, it is just using the synchronous API and works fine.  
  
The unit test uses xUnit and FakeItEasy. I create my fakes in the constructor, including the MockCachingService:  
  
```
        public AuthOrchestratorTests()
        {
            _appUserService = A.Fake<IAppUserService>();
            _membershipService = A.Fake<IMembershipService>();
            _appCache = new MockCachingService();
            _logger = A.Fake<ILogger>();
            _currentUser = A.Fake<ICurrentUser>();
            _auditService = A.Fake<IAuditService>();
            _authorizer = A.Fake<IAuthorizer>();
        }
```

The unit test itself is:  
```
	public async Task AuthenticateLogin_Returns_Fail_Where_Login_()
	{
		var loginDto = LoginDtoBuilder.Default().WithUsername(GetRandom.String()).Build();
		var userLogin = UserLoginDtoBuilder.Simple().Build();
		var cacheKey = string.Concat(CacheKeys.FacilityForCarpsUrl, userLogin.PrimaryFacilityID);
		var facilityOnLoginDto = FacilityOnLoginDtoBuilder.Default()
			.WithActive(false)
			.WithFacilityId(userLogin.PrimaryFacilityID.Value)
			.Build();

		A.CallTo(() => _appUserService.GetUserLoginDto(loginDto.Username)).Returns(userLogin);
		A.CallTo(() => _membershipService.SignInUser(loginDto.Username, loginDto.Password))
			.Returns(SignInResult.Success);
		A.CallTo(() => _appUserService.GetFacilityAdminDto(userLogin.PrimaryFacilityID.Value))
			.Returns(facilityOnLoginDto);

		var authOrchestrator = new AuthOrchestrator(
			_appUserService,
			_membershipService,
			_appCache,
			_authorizer,
			_logger,
			_currentUser,
			_auditService
		);

		var actionResult = await authOrchestrator.AuthenticateLogin(loginDto);
		
		actionResult.ShouldBeOfType<LogInFailedActionResult>();
	}

```

The test bombs out at the line of code where the IAppCache GetOrAdd method is invoked and the exception details is:    
    

> Test Name:	CarpsAbatements.Tests.UiServices.AuthOrchestratorTests.AuthenticateLogin_Returns_Fail_Where_Login_
Test FullName:	CarpsAbatements.Tests.CarpsAbatements.Tests.UiServices.AuthOrchestratorTests.CarpsAbatements.Tests.UiServices.AuthOrchestratorTests.AuthenticateLogin_Returns_Fail_Where_Login_
Test Source:	E:\Repos\Abatements\CarpsAbatements\CarpsAbatements.Tests\UiServices\AuthOrchestratorTests.cs : line 96
Test Outcome:	Failed
Test Duration:	0:00:00

> Test Name:	CarpsAbatements.Tests.UiServices.AuthOrchestratorTests.AuthenticateLogin_Returns_Fail_Where_Login_
Test Outcome:	Failed
Result StackTrace:	
at LazyCache.AppCacheExtenions.GetOrAdd[T](IAppCache cache, String key, Func`1 addItemFactory)
   at CarpsAbatements.UiServices.Orchestration.AuthOrchestrator.AuthenticateLogin(LoginDto user) in E:\Repos\Abatements\CarpsAbatements\CarpsAbatements\UiServices\Orchestration\AuthOrchestrator.cs:line 69
   at CarpsAbatements.Tests.UiServices.AuthOrchestratorTests.AuthenticateLogin_Returns_Fail_Where_Login_() in E:\Repos\Abatements\CarpsAbatements\CarpsAbatements.Tests\UiServices\AuthOrchestratorTests.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.

The expected outcome was for the `FacilityOnLoginDto` object to be returned by the Fake, as set up by the FakeItEasy fake for the `AppUserService`.

(By all means, let me know if I am not using it properly. It was not easy finding doco on preferred usage.)

**Comment by DavidRogersDev** [comment]
Just to add a further piece of information.
This only occurs when I use the exe restored by Nuget.

That is, I cloned the repo and added it to my project, in a bid to debug the problem and the exception was not thrown when I ran it through the code. 

I'm using ASP.NET Core 2.2

**Comment by alastairtree** [comment]
Hi @DavidRogersDev.

I havce tried to recreate your issue using a minimal reproduction in a console app in the code below but cannot seem to recreate the issue. I suspect the null reference is in your code rather than LazyCache but could you have a look at the below and see if I have recreated anything wrongly, and let me know the simplest way to reproduce your problem? 

Thanks.

```cmd
makedir deletemelazy
cd deletemelazy
dotnet new console
dotnet add package lazycache
```

And then in `Program.cs` place the following:
```csharp
using System;
using LazyCache;
using LazyCache.Mocks;

namespace deletemelazy
{
    class Program
    {
        static void Main(string[] args)
        {
            IAppCache cache = new MockCachingService();
            var result = cache.GetOrAdd("key", () => {
                Console.WriteLine("Hello from the cache!");
                return new object();
            });
            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
    }
}
```

**Comment by alastairtree** [comment]
Closing as no response, please file another issue if you are having issues. Thanks.
