### ISSUE TITLE
Microsoft Extension Version [2.2 versus 3] Issues

### ISSUE THREAD

**Issue by RalfKoch** [alastairtree/LazyCache#99]
After moving my solution and projects up to .NET 4.7.2 and subsequently updating LazyCache to the appropriate Version I had to update the Microsoft Extensions as well.
But that does not work well since it somehow still looks for version 2.2.0.0 and i cannot figure out where i have to change that. Every reference or setting pointed to the new version.
It only works when i stay with the older version of lazyCache which relies on MS Extensions Version 2.2.0.0. and below .NET 4.7.2.
Am I missing something here?
Did anyone else run into that problem?
I would really like to continue using LazyCache.

**Comment by Jogai** [comment]
I use .NET 4.7.2 with those packages and its working fine. Currently my nuget package config is like this (removed the non cache packages for brevity) :

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CacheManager.Core" version="1.2.0" targetFramework="net472" />
  <package id="CacheManager.Microsoft.Extensions.Caching.Memory" version="1.2.0" targetFramework="net472" />
  <package id="CacheManager.Web" version="1.2.0" targetFramework="net472" />
  <package id="LazyCache" version="2.0.1" targetFramework="net472" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="2.2.0" targetFramework="net472" allowedVersions="(1.0.0, 3.0.0)" />
  <package id="Microsoft.Extensions.Caching.Memory" version="2.2.0" targetFramework="net472" allowedVersions="(1.0.0, 3.0.0)" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net472" allowedVersions="(1.0.0, 3.0.0)" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net472" allowedVersions="(1.0.0, 3.0.0)" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net472" allowedVersions="(1.0.0, 3.0.0)" />  
</packages>
```

**Comment by RalfKoch** [comment]
That is correct, it worked with 4.7.2 and MS Versions 2.2 but when you are going to update LazyCache then it will update the MS to 3.x and then it is not working anymore.
Maybe you should try that as well.
You can go back to the older version of LazyCache with MS 2.2.
